# 只有新损失
name: train_MSDSRNet_testP
model_type: MSDSRNet_eight_Model
scale: 4
num_gpu: auto  # auto: can infer from your visible devices automatically. official: 4 GPUs
manual_seed: 0

# ----------------- options for synthesizing training data in RealESRGANModel ----------------- #
# USM the ground-truth

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: CycleSRGANPairedDataset
    dataroot_gt: datasets/DF2K
    dataroot_lq: datasets/DF2K
    meta_info: datasets/DF2K/meta_info_DF2K_pair.txt
    io_backend:
      type: disk


    gt_size: 196
    use_hflip: True
    use_rot: False

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 22
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  # Uncomment these for validation
  val:
    name: validation
    type: PairedImageDataset
    dataroot_gt: path_to_gt
    dataroot_lq: path_to_lq
    io_backend:
      type: disk

# network structures


network_P:
  type: Predictor_eight
# UY↓Y
network_U:
  type: MSDSRNet_eight
  




# path
path:
  # use the pre-trained Real-ESRNet model
  pretrain_network_P:  experiments/debug/net_P_37.pth
  pretrain_network_U: 
  param_key_g: params_ema
  param_key_p: params
  strict_load_g: false
  resume_state: ~





# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 4e-4
    weight_decay: 0
    betas: [0.9, 0.99]
 


  scheduler:
    type: MultiStepLR
    milestones: [100000,200000,300000,400000,500000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  # regress_opt:
  #   type: CrossEntropyLoss
  #   loss_weight: 1.0
  #   # reduction: mean
  


# Uncomment these for validation
# validation settings
val:
  val_freq: !!float 1e3
  save_img: False

  metrics:
    psnr: # metric name
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
